version: 0.2
phases:
  build:
    commands:
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name buddy-chat-sam --resolve-s3 --capabilities CAPABILITY_IAM